# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python27\Scripts\GUI\Evapor_properties.ui'
#
# Created: Mon Apr 24 09:02:09 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Validator(object):
    def NumValidator(self,LineEdit):
        LineEdit.setValidator(QtGui.QDoubleValidator(0,100000,2,LineEdit))

class Ui_Dialog(object):
    def setupUi(self,name,item,Dialog):
        global nameDialog
        global title_name

        Vali = Validator()
        nameDialog=name
        title_name=str(item.label.toPlainText())
        
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(465, 398)

        self.Layout=QtGui.QVBoxLayout(Dialog)

        self.tabWidget_Evap = QtGui.QTabWidget(Dialog)
        self.tabWidget_Evap.setGeometry(QtCore.QRect(3, 31, 461, 361))
        self.tabWidget_Evap.setObjectName(_fromUtf8("tabWidget_Evap"))
        self.Evap_tab_1 = QtGui.QWidget()
        self.Evap_tab_1.setObjectName(_fromUtf8("Evap_tab_1"))
        self.Evapor_propert_GrBx = QtGui.QGroupBox(self.Evap_tab_1)
        self.Evapor_propert_GrBx.setGeometry(QtCore.QRect(10, 10, 211, 231))
        self.Evapor_propert_GrBx.setObjectName(_fromUtf8("Evapor_propert_GrBx"))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Evapor_propert_GrBx.sizePolicy().hasHeightForWidth())
        self.Evapor_propert_GrBx.setSizePolicy(sizePolicy)


        self.Cross_Sectional_Area = QtGui.QLineEdit(self.Evapor_propert_GrBx)
        self.Cross_Sectional_Area.setGeometry(QtCore.QRect(150, 41, 51, 20))
        self.Cross_Sectional_Area.setReadOnly(False)
        self.Cross_Sectional_Area.setObjectName(_fromUtf8("Cross_Sectional_Area"))
        self.label_Heat_Area = QtGui.QLabel(self.Evapor_propert_GrBx)
        self.label_Heat_Area.setGeometry(QtCore.QRect(9, 95, 141, 16))
        self.label_Heat_Area.setObjectName(_fromUtf8("label_Heat_Area"))
        self.Heat_Area = QtGui.QLineEdit(self.Evapor_propert_GrBx)
        self.Heat_Area.setGeometry(QtCore.QRect(150, 95, 51, 20))
        self.Heat_Area.setReadOnly(False)
        self.Heat_Area.setObjectName(_fromUtf8("Heat_Area"))
        self.comBox_Area_or_Pipes = QtGui.QComboBox(self.Evapor_propert_GrBx)
        self.comBox_Area_or_Pipes.setGeometry(QtCore.QRect(9, 64, 191, 22))
        self.comBox_Area_or_Pipes.setObjectName(_fromUtf8("comBox_Area_or_Pipes"))
        self.comBox_Area_or_Pipes.addItem("--Seleccione dato--")
        self.comBox_Area_or_Pipes.addItem(_translate("Dialog", "Dato de área de calentamiento",None))
        self.comBox_Area_or_Pipes.addItem("Dato de tubos en calandria")
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comBox_Area_or_Pipes.sizePolicy().hasHeightForWidth())
        self.comBox_Area_or_Pipes.setSizePolicy(sizePolicy)


        self.label_Cross_Sectional_Area = QtGui.QLabel(self.Evapor_propert_GrBx)
        self.label_Cross_Sectional_Area.setGeometry(QtCore.QRect(10, 42, 141, 16))
        self.label_Cross_Sectional_Area.setObjectName(_fromUtf8("label_Cross_Sectional_Area"))
        self.Volumen = QtGui.QLineEdit(self.Evapor_propert_GrBx)
        self.Volumen.setGeometry(QtCore.QRect(150, 18, 51, 20))
        self.Volumen.setReadOnly(False)
        self.Volumen.setObjectName(_fromUtf8("Volumen"))
        self.label_Volumen = QtGui.QLabel(self.Evapor_propert_GrBx)
        self.label_Volumen.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_Volumen.setObjectName(_fromUtf8("label_Volumen"))
        self.Pipe_Lenght = QtGui.QLineEdit(self.Evapor_propert_GrBx)
        self.Pipe_Lenght.setGeometry(QtCore.QRect(150, 175, 51, 20))
        self.Pipe_Lenght.setReadOnly(False)
        self.Pipe_Lenght.setObjectName(_fromUtf8("Pipe_Lenght"))
        self.label_Pipe_Lenght = QtGui.QLabel(self.Evapor_propert_GrBx)
        self.label_Pipe_Lenght.setGeometry(QtCore.QRect(10, 170, 141, 31))
        self.label_Pipe_Lenght.setObjectName(_fromUtf8("label_Pipe_Lenght"))
        self.N_pipes = QtGui.QLineEdit(self.Evapor_propert_GrBx)
        self.N_pipes.setGeometry(QtCore.QRect(150, 147, 51, 20))
        self.N_pipes.setReadOnly(False)
        self.N_pipes.setObjectName(_fromUtf8("N_pipes"))
        self.label_N_pipes = QtGui.QLabel(self.Evapor_propert_GrBx)
        self.label_N_pipes.setGeometry(QtCore.QRect(10, 148, 141, 16))
        self.label_N_pipes.setObjectName(_fromUtf8("label_N_pipes"))
        self.Pipe_Diameter = QtGui.QLineEdit(self.Evapor_propert_GrBx)
        self.Pipe_Diameter.setGeometry(QtCore.QRect(150, 121, 51, 20))
        self.Pipe_Diameter.setReadOnly(False)
        self.Pipe_Diameter.setObjectName(_fromUtf8("Pipe_Diameter"))
        self.label_Pipe_Diameter = QtGui.QLabel(self.Evapor_propert_GrBx)
        self.label_Pipe_Diameter.setGeometry(QtCore.QRect(10, 117, 141, 31))
        self.label_Pipe_Diameter.setObjectName(_fromUtf8("label_Pipe_Diameter"))
        self.label_Downtake_Diameter = QtGui.QLabel(self.Evapor_propert_GrBx)
        self.label_Downtake_Diameter.setGeometry(QtCore.QRect(10, 200, 141, 31))
        self.label_Downtake_Diameter.setObjectName(_fromUtf8("label_Downtake_Diameter"))
        self.Downtake_Diameter = QtGui.QLineEdit(self.Evapor_propert_GrBx)
        self.Downtake_Diameter.setGeometry(QtCore.QRect(150, 205, 51, 20))
        self.Downtake_Diameter.setReadOnly(False)
        self.Downtake_Diameter.setObjectName(_fromUtf8("Downtake_Diameter"))
       

        self.Initial_Conditions_GrBx = QtGui.QGroupBox(self.Evap_tab_1)
        self.Initial_Conditions_GrBx.setGeometry(QtCore.QRect(229, 10, 221, 101))
        self.Initial_Conditions_GrBx.setObjectName(_fromUtf8("Initial_Conditions_GrBx"))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Initial_Conditions_GrBx.sizePolicy().hasHeightForWidth())
        self.Initial_Conditions_GrBx.setSizePolicy(sizePolicy)


        self.Output_Juice_Brix = QtGui.QLineEdit(self.Initial_Conditions_GrBx)
        self.Output_Juice_Brix.setGeometry(QtCore.QRect(167, 18, 51, 20))
        self.Output_Juice_Brix.setObjectName(_fromUtf8("Output_Juice_Brix"))
        # self.groupBox_7 = QtGui.QGroupBox(self.Initial_Conditions_GrBx)
        # self.groupBox_7.setGeometry(QtCore.QRect(243, 13, 181, 80))
        # self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_Output_Juice_Brix = QtGui.QLabel(self.Initial_Conditions_GrBx)
        self.label_Output_Juice_Brix.setGeometry(QtCore.QRect(9, 20, 141, 16))
        self.label_Output_Juice_Brix.setObjectName(_fromUtf8("label_Output_Juice_Brix"))
        self.Output_Juice_Flow = QtGui.QLineEdit(self.Initial_Conditions_GrBx)
        self.Output_Juice_Flow.setGeometry(QtCore.QRect(167, 47, 51, 20))
        self.Output_Juice_Flow.setObjectName(_fromUtf8("Output_Juice_Flow"))
        self.label_Output_Juice_Flow = QtGui.QLabel(self.Initial_Conditions_GrBx)
        self.label_Output_Juice_Flow.setGeometry(QtCore.QRect(9, 42, 141, 31))
        self.label_Output_Juice_Flow.setObjectName(_fromUtf8("label_Output_Juice_Flow"))
        self.Evaporator_Level = QtGui.QLineEdit(self.Initial_Conditions_GrBx)
        self.Evaporator_Level.setGeometry(QtCore.QRect(167, 74, 51, 20))
        self.Evaporator_Level.setObjectName(_fromUtf8("Evaporator_Level"))
        self.label_Evaporator_Level = QtGui.QLabel(self.Initial_Conditions_GrBx)
        self.label_Evaporator_Level.setGeometry(QtCore.QRect(10, 76, 161, 16))
        self.label_Evaporator_Level.setObjectName(_fromUtf8("label_Evaporator_Level"))
        # self.Layout_Initial_Conditions_GrBx=QtGui.QVBoxLayout(Dialog)
        # self.Layout_Initial_Conditions_GrBx.addWidget(self.label_Volumen,0,0)
        # self.Layout_Initial_Conditions_GrBx.addWidget(self.Volumen,0,1)
        # self.Layout_Initial_Conditions_GrBx.addWidget(self.label_Cross_Sectional_Area,1,0)
        # self.Layout_Initial_Conditions_GrBx.addWidget(self.Cross_Sectional_Area,1,1)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,2,0)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,2,1)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,3,0)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,3,1)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,4,0)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,4,1)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,5,0)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,5,1)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,6,0)
        # self.Layout_Initial_Conditions_GrBx.addWidget(,6,1)



        self.OKButton_Evap = QtGui.QPushButton(self.Evap_tab_1)
        self.OKButton_Evap.setGeometry(QtCore.QRect(312, 307, 131, 23))
        self.OKButton_Evap.setObjectName(_fromUtf8("OKButton_Evap"))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OKButton_Evap.sizePolicy().hasHeightForWidth())
        self.OKButton_Evap.setSizePolicy(sizePolicy)

        self.tabWidget_Evap.addTab(self.Evap_tab_1, _fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(self.Evap_tab_1)
        self.gridLayout.addWidget(self.Evapor_propert_GrBx, 0, 0)
        self.gridLayout.addWidget(self.Initial_Conditions_GrBx, 0, 1)
        self.gridLayout.addWidget(self.OKButton_Evap, 1, 1)





        self.Evap_tab_2 = QtGui.QWidget()
        self.Evap_tab_2.setObjectName(_fromUtf8("Evap_tab_2"))
        self.Input_fluid_GrBx = QtGui.QGroupBox(self.Evap_tab_2)
        self.Input_fluid_GrBx.setGeometry(QtCore.QRect(20, 8, 191, 161))
        self.Input_fluid_GrBx.setObjectName(_fromUtf8("Input_fluid_GrBx"))
        self.label_InFluid_Flow = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Flow.setGeometry(QtCore.QRect(10, 21, 131, 16))
        self.label_InFluid_Flow.setObjectName(_fromUtf8("label_InFluid_Flow"))
        self.label_InFluid_Temp = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Temp.setGeometry(QtCore.QRect(10, 43, 121, 16))
        self.label_InFluid_Temp.setObjectName(_fromUtf8("label_InFluid_Temp"))
        self.label_InFluid_Brix = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Brix.setGeometry(QtCore.QRect(10, 66, 121, 16))
        self.label_InFluid_Brix.setObjectName(_fromUtf8("label_InFluid_Brix"))
        self.label_InFluid_Purity = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Purity.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.label_InFluid_Purity.setObjectName(_fromUtf8("label_InFluid_Purity"))
        self.InFluid_Temp = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Temp.setGeometry(QtCore.QRect(140, 42, 41, 20))
        self.InFluid_Temp.setReadOnly(True)
        self.InFluid_Temp.setObjectName(_fromUtf8("InFluid_Temp"))
        self.InFluid_Flow = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Flow.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.InFluid_Flow.setReadOnly(True)
        self.InFluid_Flow.setObjectName(_fromUtf8("InFluid_Flow"))
        self.InFluid_Purity = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Purity.setGeometry(QtCore.QRect(140, 108, 41, 20))
        self.InFluid_Purity.setReadOnly(True)
        self.InFluid_Purity.setObjectName(_fromUtf8("InFluid_Purity"))
        self.InFluid_Brix = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Brix.setGeometry(QtCore.QRect(140, 64, 41, 20))
        self.InFluid_Brix.setReadOnly(True)
        self.InFluid_Brix.setObjectName(_fromUtf8("InFluid_Brix"))
        self.label_InFluid_InsolubleSolids = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_InsolubleSolids.setGeometry(QtCore.QRect(10, 88, 121, 16))
        self.label_InFluid_InsolubleSolids.setObjectName(_fromUtf8("label_InFluid_InsolubleSolids"))
        self.InFluid_InsolubleSolids_2 = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_InsolubleSolids_2.setGeometry(QtCore.QRect(140, 86, 41, 20))
        self.InFluid_InsolubleSolids_2.setReadOnly(True)
        self.InFluid_InsolubleSolids_2.setObjectName(_fromUtf8("InFluid_InsolubleSolids_2"))
        self.label_InFluid_pH = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_pH.setGeometry(QtCore.QRect(10, 132, 121, 16))
        self.label_InFluid_pH.setObjectName(_fromUtf8("label_InFluid_pH"))
        self.InFluid_pH = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_pH.setGeometry(QtCore.QRect(140, 130, 41, 20))
        self.InFluid_pH.setReadOnly(True)
        self.InFluid_pH.setObjectName(_fromUtf8("InFluid_pH"))
        self.Output_fluid_GrBx = QtGui.QGroupBox(self.Evap_tab_2)
        self.Output_fluid_GrBx.setGeometry(QtCore.QRect(233, 8, 191, 161))
        self.Output_fluid_GrBx.setObjectName(_fromUtf8("Output_fluid_GrBx"))
        self.label_OutFluid_Flow = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Flow.setGeometry(QtCore.QRect(10, 21, 131, 16))
        self.label_OutFluid_Flow.setObjectName(_fromUtf8("label_OutFluid_Flow"))
        self.label_OutFluid_Temp = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Temp.setGeometry(QtCore.QRect(10, 43, 121, 16))
        self.label_OutFluid_Temp.setObjectName(_fromUtf8("label_OutFluid_Temp"))
        self.label_OutFluid_Brix = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Brix.setGeometry(QtCore.QRect(10, 66, 121, 16))
        self.label_OutFluid_Brix.setObjectName(_fromUtf8("label_OutFluid_Brix"))
        self.OutFluid_Temp = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Temp.setGeometry(QtCore.QRect(140, 42, 41, 20))
        self.OutFluid_Temp.setReadOnly(True)
        self.OutFluid_Temp.setObjectName(_fromUtf8("OutFluid_Temp"))
        self.OutFluid_Flow = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Flow.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.OutFluid_Flow.setReadOnly(True)
        self.OutFluid_Flow.setObjectName(_fromUtf8("OutFluid_Flow"))
        self.OutFluid_Brix = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Brix.setGeometry(QtCore.QRect(140, 64, 41, 20))
        self.OutFluid_Brix.setReadOnly(True)
        self.OutFluid_Brix.setObjectName(_fromUtf8("OutFluid_Brix"))
        self.label_OutFluid_Purity = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Purity.setGeometry(QtCore.QRect(10, 109, 121, 16))
        self.label_OutFluid_Purity.setObjectName(_fromUtf8("label_OutFluid_Purity"))
        self.OutFluid_pH = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_pH.setGeometry(QtCore.QRect(140, 129, 41, 20))
        self.OutFluid_pH.setReadOnly(True)
        self.OutFluid_pH.setObjectName(_fromUtf8("OutFluid_pH"))
        self.OutFluid_InsolubleSolids = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_InsolubleSolids.setGeometry(QtCore.QRect(140, 85, 41, 20))
        self.OutFluid_InsolubleSolids.setReadOnly(True)
        self.OutFluid_InsolubleSolids.setObjectName(_fromUtf8("OutFluid_InsolubleSolids"))
        self.OutFluid_Purity = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Purity.setGeometry(QtCore.QRect(140, 107, 41, 20))
        self.OutFluid_Purity.setReadOnly(True)
        self.OutFluid_Purity.setObjectName(_fromUtf8("OutFluid_Purity"))
        self.label_OutFluid_InsolubleSolids = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_InsolubleSolids.setGeometry(QtCore.QRect(10, 87, 121, 16))
        self.label_OutFluid_InsolubleSolids.setObjectName(_fromUtf8("label_OutFluid_InsolubleSolids"))
        self.label_OutFluid_pH = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_pH.setGeometry(QtCore.QRect(10, 131, 121, 16))
        self.label_OutFluid_pH.setObjectName(_fromUtf8("label_OutFluid_pH"))
        self.Condensed_steam_GrBx = QtGui.QGroupBox(self.Evap_tab_2)
        self.Condensed_steam_GrBx.setGeometry(QtCore.QRect(234, 170, 191, 81))
        self.Condensed_steam_GrBx.setObjectName(_fromUtf8("Condensed_steam_GrBx"))
        self.CondStm_Flow = QtGui.QLineEdit(self.Condensed_steam_GrBx)
        self.CondStm_Flow.setGeometry(QtCore.QRect(140, 15, 41, 20))
        self.CondStm_Flow.setReadOnly(True)
        self.CondStm_Flow.setObjectName(_fromUtf8("CondStm_Flow"))
        self.label_CondStm_Flow = QtGui.QLabel(self.Condensed_steam_GrBx)
        self.label_CondStm_Flow.setGeometry(QtCore.QRect(16, 18, 121, 16))
        self.label_CondStm_Flow.setObjectName(_fromUtf8("label_CondStm_Flow"))
        self.CondStm_Temp = QtGui.QLineEdit(self.Condensed_steam_GrBx)
        self.CondStm_Temp.setGeometry(QtCore.QRect(140, 59, 41, 20))
        self.CondStm_Temp.setReadOnly(True)
        self.CondStm_Temp.setObjectName(_fromUtf8("CondStm_Temp"))
        self.CondStm_Press = QtGui.QLineEdit(self.Condensed_steam_GrBx)
        self.CondStm_Press.setGeometry(QtCore.QRect(140, 37, 41, 20))
        self.CondStm_Press.setReadOnly(True)
        self.CondStm_Press.setObjectName(_fromUtf8("CondStm_Press"))
        self.label_CondStm_Press = QtGui.QLabel(self.Condensed_steam_GrBx)
        self.label_CondStm_Press.setGeometry(QtCore.QRect(16, 40, 131, 16))
        self.label_CondStm_Press.setObjectName(_fromUtf8("label_CondStm_Press"))
        self.label_CondStm_Temp = QtGui.QLabel(self.Condensed_steam_GrBx)
        self.label_CondStm_Temp.setGeometry(QtCore.QRect(16, 61, 121, 16))
        self.label_CondStm_Temp.setObjectName(_fromUtf8("label_CondStm_Temp"))
        self.Input_Steam_GrBx = QtGui.QGroupBox(self.Evap_tab_2)
        self.Input_Steam_GrBx.setGeometry(QtCore.QRect(18, 170, 191, 81))
        self.Input_Steam_GrBx.setObjectName(_fromUtf8("Input_Steam_GrBx"))
        self.label_InStm_Flow = QtGui.QLabel(self.Input_Steam_GrBx)
        self.label_InStm_Flow.setGeometry(QtCore.QRect(10, 18, 131, 16))
        self.label_InStm_Flow.setObjectName(_fromUtf8("label_InStm_Flow"))
        self.label_InStm_Press = QtGui.QLabel(self.Input_Steam_GrBx)
        self.label_InStm_Press.setGeometry(QtCore.QRect(10, 38, 121, 16))
        self.label_InStm_Press.setObjectName(_fromUtf8("label_InStm_Press"))
        self.InStm_Press = QtGui.QLineEdit(self.Input_Steam_GrBx)
        self.InStm_Press.setGeometry(QtCore.QRect(139, 36, 41, 20))
        self.InStm_Press.setReadOnly(True)
        self.InStm_Press.setObjectName(_fromUtf8("InStm_Press"))
        self.InStm_Flow = QtGui.QLineEdit(self.Input_Steam_GrBx)
        self.InStm_Flow.setGeometry(QtCore.QRect(139, 14, 41, 20))
        self.InStm_Flow.setReadOnly(True)
        self.InStm_Flow.setObjectName(_fromUtf8("InStm_Flow"))
        self.label_InStm_Temp = QtGui.QLabel(self.Input_Steam_GrBx)
        self.label_InStm_Temp.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_InStm_Temp.setObjectName(_fromUtf8("label_InStm_Temp"))
        self.InStm_Temp = QtGui.QLineEdit(self.Input_Steam_GrBx)
        self.InStm_Temp.setGeometry(QtCore.QRect(139, 58, 41, 20))
        self.InStm_Temp.setReadOnly(True)
        self.InStm_Temp.setObjectName(_fromUtf8("InStm_Temp"))
        self.Output_Steam_GrBx = QtGui.QGroupBox(self.Evap_tab_2)
        self.Output_Steam_GrBx.setGeometry(QtCore.QRect(18, 258, 411, 71))
        self.Output_Steam_GrBx.setObjectName(_fromUtf8("Output_Steam_GrBx"))
        self.OutStm_Flow = QtGui.QLineEdit(self.Output_Steam_GrBx)
        self.OutStm_Flow.setGeometry(QtCore.QRect(139, 19, 41, 20))
        self.OutStm_Flow.setReadOnly(True)
        self.OutStm_Flow.setObjectName(_fromUtf8("OutStm_Flow"))
        self.OutStm_Press = QtGui.QLineEdit(self.Output_Steam_GrBx)
        self.OutStm_Press.setGeometry(QtCore.QRect(139, 46, 41, 20))
        self.OutStm_Press.setReadOnly(True)
        self.OutStm_Press.setObjectName(_fromUtf8("OutStm_Press"))
        self.OutStm_Temp = QtGui.QLineEdit(self.Output_Steam_GrBx)
        self.OutStm_Temp.setGeometry(QtCore.QRect(356, 18, 41, 20))
        self.OutStm_Temp.setReadOnly(True)
        self.OutStm_Temp.setObjectName(_fromUtf8("OutStm_Temp"))
        self.label_OutStm_Flow = QtGui.QLabel(self.Output_Steam_GrBx)
        self.label_OutStm_Flow.setGeometry(QtCore.QRect(10, 21, 131, 16))
        self.label_OutStm_Flow.setObjectName(_fromUtf8("label_OutStm_Flow"))
        self.label_OutStm_Press = QtGui.QLabel(self.Output_Steam_GrBx)
        self.label_OutStm_Press.setGeometry(QtCore.QRect(10, 47, 121, 16))
        self.label_OutStm_Press.setObjectName(_fromUtf8("label_OutStm_Press"))
        self.label_OutStm_Temp = QtGui.QLabel(self.Output_Steam_GrBx)
        self.label_OutStm_Temp.setGeometry(QtCore.QRect(230, 21, 121, 16))
        self.label_OutStm_Temp.setObjectName(_fromUtf8("label_OutStm_Temp"))
        


        self.tabWidget_Evap.addTab(self.Evap_tab_2, _fromUtf8(""))
        self.Evap_tab_3 = QtGui.QWidget()
        self.Evap_tab_3.setObjectName(_fromUtf8("Evap_tab_3"))
        self.comBox_InterestVariable = QtGui.QComboBox(self.Evap_tab_3)
        self.comBox_InterestVariable.setGeometry(QtCore.QRect(10, 10, 151, 22))
        self.comBox_InterestVariable.setObjectName(_fromUtf8("comBox_InterestVariable"))
        self.comBox_InterestVariable.addItem("Brix de jugo de salida")
        self.comBox_InterestVariable.addItem("Flujo de jugo de salida")
        self.comBox_InterestVariable.addItem("Nivel en evaporador")
        self.tabWidget_Evap.addTab(self.Evap_tab_3, _fromUtf8(""))
        self.comBox_Selector_Type_Evap = QtGui.QComboBox(Dialog)
        self.comBox_Selector_Type_Evap.setGeometry(QtCore.QRect(9, 6, 451, 22))
        self.comBox_Selector_Type_Evap.setObjectName(_fromUtf8("comBox_Selector_Type_Evap"))
        self.comBox_Selector_Type_Evap.addItem("--Seleccione tipo de evaporador--")
        self.comBox_Selector_Type_Evap.addItem("Evporador Robert")
        self.comBox_Selector_Type_Evap.addItem("Evporador Kestner")
        self.comBox_Selector_Type_Evap.addItem("Evporador Falling Film")

        self.Layout.addWidget(self.comBox_Selector_Type_Evap)
        self.Layout.addWidget(self.tabWidget_Evap)
        self.retranslateUi(Dialog)
        self.tabWidget_Evap.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Parametros "+title_name, None))
        self.Evapor_propert_GrBx.setTitle(_translate("Dialog", "Propiedades físicas", None))
        self.label_Heat_Area.setText(_translate("Dialog", "Área de calentamiento [m2]", None))
        self.label_Cross_Sectional_Area.setText(_translate("Dialog", "Área transversal [m2]", None))
        self.label_Volumen.setText(_translate("Dialog", "Volumen [m3]", None))
        self.label_Pipe_Lenght.setText(_translate("Dialog", "Longitud tubo de calandria \n"
"[m]", None))
        self.label_N_pipes.setText(_translate("Dialog", "N° tubos de calandria", None))
        self.label_Pipe_Diameter.setText(_translate("Dialog", "Diámetro tubo de calandria \n"
"[in]", None))
        self.label_Downtake_Diameter.setText(_translate("Dialog", "Diámetro downtake [in]", None))
        self.Initial_Conditions_GrBx.setTitle(_translate("Dialog", "Condiciones iniciales", None))
        # self.groupBox_7.setTitle(_translate("Dialog", "Steam input", None))
        self.label_Output_Juice_Brix.setText(_translate("Dialog", "Brix de jugo de salida [kg/kg]", None))
        self.label_Output_Juice_Flow.setText(_translate("Dialog", "Flujo másico de jugo de salida\n"
"[t/h]", None))
        self.label_Evaporator_Level.setText(_translate("Dialog", "Nivel en evaporador [m/m]", None))
        self.OKButton_Evap.setText(_translate("Dialog", "Aceptar", None))
        self.tabWidget_Evap.setTabText(self.tabWidget_Evap.indexOf(self.Evap_tab_1), _translate("Dialog", "Propiedades físicas", None))
        self.Input_fluid_GrBx.setTitle(_translate("Dialog", "Fluido de entrada", None))
        self.label_InFluid_Flow.setText(_translate("Dialog", "Flujo másico [t/h]", None))
        self.label_InFluid_Temp.setText(_translate("Dialog", "Temperatura [°C]", None))
        self.label_InFluid_Brix.setText(_translate("Dialog", "Brix [kg/kg]", None))
        self.label_InFluid_Purity.setText(_translate("Dialog", "Pureza [kg/kg]", None))
        self.label_InFluid_InsolubleSolids.setText(_translate("Dialog", "Sólidos insolubles [kg/kg]", None))
        self.label_InFluid_pH.setText(_translate("Dialog", "pH ", None))
        self.Output_fluid_GrBx.setTitle(_translate("Dialog", "Fluido de salida", None))
        self.label_OutFluid_Flow.setText(_translate("Dialog", "Flujo másico [t/h]", None))
        self.label_OutFluid_Temp.setText(_translate("Dialog", "Temperatura [°C]", None))
        self.label_OutFluid_Brix.setText(_translate("Dialog", "Brix [kg/kg]", None))
        self.label_OutFluid_Purity.setText(_translate("Dialog", "Pureza [kg/kg]", None))
        self.label_OutFluid_InsolubleSolids.setText(_translate("Dialog", "Sólidos insolubles [kg/kg]", None))
        self.label_OutFluid_pH.setText(_translate("Dialog", "pH ", None))
        self.Condensed_steam_GrBx.setTitle(_translate("Dialog", "Vapor condensado ", None))
        self.label_CondStm_Flow.setText(_translate("Dialog", "Flujo másico [t/h]", None))
        self.label_CondStm_Press.setText(_translate("Dialog", "Presión [Pa]", None))
        self.label_CondStm_Temp.setText(_translate("Dialog", "Temperatura [°C]", None))
        self.Input_Steam_GrBx.setTitle(_translate("Dialog", "Vapor vivo", None))
        self.label_InStm_Flow.setText(_translate("Dialog", "Flujo másico [t/h]", None))
        self.label_InStm_Press.setText(_translate("Dialog", "Presión [Pa]", None))
        self.label_InStm_Temp.setText(_translate("Dialog", "Temperatura [°C]", None))
        self.Output_Steam_GrBx.setTitle(_translate("Dialog", "Vapor vegetal", None))
        self.label_OutStm_Flow.setText(_translate("Dialog", "Flujo másico [t/h]", None))
        self.label_OutStm_Press.setText(_translate("Dialog", "Presión [Pa]", None))
        self.label_OutStm_Temp.setText(_translate("Dialog", "Temperatura [°C]", None))
        self.tabWidget_Evap.setTabText(self.tabWidget_Evap.indexOf(self.Evap_tab_2), _translate("Dialog", "Variables de proceso", None))
        self.tabWidget_Evap.setTabText(self.tabWidget_Evap.indexOf(self.Evap_tab_3), _translate("Dialog", "Gráfica", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi("Calentador",Dialog)
    Dialog.show()
    sys.exit(app.exec_())

