# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python27\Scripts\GUI\Tank_properties.ui'
#
# Created: Tue Apr 25 08:34:46 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
class Validator(object):
    def NumValidator(self,LineEdit):
        LineEdit.setValidator(QtGui.QDoubleValidator(0,100000,2,LineEdit))
        
class Ui_Dialog(object):
    def setupUi(self,name, Dialog):
        global nameDialog
        Vali = Validator()

        nameDialog=name 

        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(442, 280)
        self.Tank_tabWidget = QtGui.QTabWidget(Dialog)
        self.Tank_tabWidget.setGeometry(QtCore.QRect(10, 10, 421, 261))
        self.Tank_tabWidget.setObjectName(_fromUtf8("Tank_tabWidget"))
        self.Tank_tab_1 = QtGui.QWidget()
        self.Tank_tab_1.setObjectName(_fromUtf8("Tank_tab_1"))
        self.Physical_properties_GrBx = QtGui.QGroupBox(self.Tank_tab_1)
        self.Physical_properties_GrBx.setGeometry(QtCore.QRect(10, 21, 181, 81))
        self.Physical_properties_GrBx.setObjectName(_fromUtf8("Physical_properties_GrBx"))
        self.Volumen = QtGui.QLineEdit(self.Physical_properties_GrBx)
        self.Volumen.setGeometry(QtCore.QRect(135, 23, 41, 20))
        self.Volumen.setObjectName(_fromUtf8("Volumen"))
        self.Cross_Sectional_Area = QtGui.QLineEdit(self.Physical_properties_GrBx)
        self.Cross_Sectional_Area.setGeometry(QtCore.QRect(135, 49, 41, 20))
        self.Cross_Sectional_Area.setObjectName(_fromUtf8("Cross_Sectional_Area"))
        self.label_Cross_Sectional_Area = QtGui.QLabel(self.Physical_properties_GrBx)
        self.label_Cross_Sectional_Area.setGeometry(QtCore.QRect(10, 51, 141, 16))
        self.label_Cross_Sectional_Area.setObjectName(_fromUtf8("label_Cross_Sectional_Area"))
        self.label_Volumen = QtGui.QLabel(self.Physical_properties_GrBx)
        self.label_Volumen.setGeometry(QtCore.QRect(10, 26, 141, 16))
        self.label_Volumen.setObjectName(_fromUtf8("label_Volumen"))
        self.Initial_conditions_GrBx = QtGui.QGroupBox(self.Tank_tab_1)
        self.Initial_conditions_GrBx.setGeometry(QtCore.QRect(218, 20, 191, 51))
        self.Initial_conditions_GrBx.setObjectName(_fromUtf8("Initial_conditions_GrBx"))
        self.Initial_Level = QtGui.QLineEdit(self.Initial_conditions_GrBx)
        self.Initial_Level.setGeometry(QtCore.QRect(138, 27, 41, 20))
        self.Initial_Level.setReadOnly(False)
        self.Initial_Level.setObjectName(_fromUtf8("Initial_Level"))
        self.label_Initial_Level = QtGui.QLabel(self.Initial_conditions_GrBx)
        self.label_Initial_Level.setGeometry(QtCore.QRect(7, 26, 131, 20))
        self.label_Initial_Level.setObjectName(_fromUtf8("label_Initial_Level"))
        self.OKButton_Tank = QtGui.QPushButton(self.Tank_tab_1)
        self.OKButton_Tank.setGeometry(QtCore.QRect(279, 206, 131, 23))
        self.OKButton_Tank.setObjectName(_fromUtf8("OKButton_Tank"))
        self.Tank_tabWidget.addTab(self.Tank_tab_1, _fromUtf8(""))
        self.Tank_tab_2 = QtGui.QWidget()
        self.Tank_tab_2.setObjectName(_fromUtf8("Tank_tab_2"))
        self.Input_fluid_GrBx = QtGui.QGroupBox(self.Tank_tab_2)
        self.Input_fluid_GrBx.setGeometry(QtCore.QRect(5, 16, 191, 161))
        self.Input_fluid_GrBx.setObjectName(_fromUtf8("Input_fluid_GrBx"))
        self.label_InFluid_Flow = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Flow.setGeometry(QtCore.QRect(10, 21, 131, 16))
        self.label_InFluid_Flow.setObjectName(_fromUtf8("label_InFluid_Flow"))
        self.label_InFluid_Temp = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Temp.setGeometry(QtCore.QRect(10, 43, 121, 16))
        self.label_InFluid_Temp.setObjectName(_fromUtf8("label_InFluid_Temp"))
        self.label_InFluid_Brix = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Brix.setGeometry(QtCore.QRect(10, 66, 121, 16))
        self.label_InFluid_Brix.setObjectName(_fromUtf8("label_InFluid_Brix"))
        self.label_InFluid_Purity = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_Purity.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.label_InFluid_Purity.setObjectName(_fromUtf8("label_InFluid_Purity"))
        self.InFluid_Temp = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Temp.setGeometry(QtCore.QRect(140, 42, 41, 20))
        self.InFluid_Temp.setReadOnly(True)
        self.InFluid_Temp.setObjectName(_fromUtf8("InFluid_Temp"))
        self.InFluid_Flow = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Flow.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.InFluid_Flow.setReadOnly(True)
        self.InFluid_Flow.setObjectName(_fromUtf8("InFluid_Flow"))
        self.InFluid_Purity = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Purity.setGeometry(QtCore.QRect(140, 108, 41, 20))
        self.InFluid_Purity.setReadOnly(True)
        self.InFluid_Purity.setObjectName(_fromUtf8("InFluid_Purity"))
        self.InFluid_Brix = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_Brix.setGeometry(QtCore.QRect(140, 64, 41, 20))
        self.InFluid_Brix.setReadOnly(True)
        self.InFluid_Brix.setObjectName(_fromUtf8("InFluid_Brix"))
        self.label_InFluid_InsolubleSolids = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_InsolubleSolids.setGeometry(QtCore.QRect(10, 88, 121, 16))
        self.label_InFluid_InsolubleSolids.setObjectName(_fromUtf8("label_InFluid_InsolubleSolids"))
        self.InFluid_InsolubleSolids_2 = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_InsolubleSolids_2.setGeometry(QtCore.QRect(140, 86, 41, 20))
        self.InFluid_InsolubleSolids_2.setReadOnly(True)
        self.InFluid_InsolubleSolids_2.setObjectName(_fromUtf8("InFluid_InsolubleSolids_2"))
        self.label_InFluid_pH = QtGui.QLabel(self.Input_fluid_GrBx)
        self.label_InFluid_pH.setGeometry(QtCore.QRect(10, 132, 121, 16))
        self.label_InFluid_pH.setObjectName(_fromUtf8("label_InFluid_pH"))
        self.InFluid_pH = QtGui.QLineEdit(self.Input_fluid_GrBx)
        self.InFluid_pH.setGeometry(QtCore.QRect(140, 130, 41, 20))
        self.InFluid_pH.setReadOnly(True)
        self.InFluid_pH.setObjectName(_fromUtf8("InFluid_pH"))
        self.Output_fluid_GrBx = QtGui.QGroupBox(self.Tank_tab_2)
        self.Output_fluid_GrBx.setGeometry(QtCore.QRect(218, 16, 191, 161))
        self.Output_fluid_GrBx.setObjectName(_fromUtf8("Output_fluid_GrBx"))
        self.label_OutFluid_Flow = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Flow.setGeometry(QtCore.QRect(10, 21, 131, 16))
        self.label_OutFluid_Flow.setObjectName(_fromUtf8("label_OutFluid_Flow"))
        self.label_OutFluid_Temp = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Temp.setGeometry(QtCore.QRect(10, 43, 121, 16))
        self.label_OutFluid_Temp.setObjectName(_fromUtf8("label_OutFluid_Temp"))
        self.label_OutFluid_Brix = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Brix.setGeometry(QtCore.QRect(10, 66, 121, 16))
        self.label_OutFluid_Brix.setObjectName(_fromUtf8("label_OutFluid_Brix"))
        self.OutFluid_Temp = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Temp.setGeometry(QtCore.QRect(140, 42, 41, 20))
        self.OutFluid_Temp.setReadOnly(True)
        self.OutFluid_Temp.setObjectName(_fromUtf8("OutFluid_Temp"))
        self.OutFluid_Flow = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Flow.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.OutFluid_Flow.setReadOnly(True)
        self.OutFluid_Flow.setObjectName(_fromUtf8("OutFluid_Flow"))
        self.OutFluid_Brix = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Brix.setGeometry(QtCore.QRect(140, 64, 41, 20))
        self.OutFluid_Brix.setReadOnly(True)
        self.OutFluid_Brix.setObjectName(_fromUtf8("OutFluid_Brix"))
        self.label_OutFluid_Purity = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_Purity.setGeometry(QtCore.QRect(10, 109, 121, 16))
        self.label_OutFluid_Purity.setObjectName(_fromUtf8("label_OutFluid_Purity"))
        self.OutFluid_pH = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_pH.setGeometry(QtCore.QRect(140, 129, 41, 20))
        self.OutFluid_pH.setReadOnly(True)
        self.OutFluid_pH.setObjectName(_fromUtf8("OutFluid_pH"))
        self.OutFluid_InsolubleSolids = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_InsolubleSolids.setGeometry(QtCore.QRect(140, 85, 41, 20))
        self.OutFluid_InsolubleSolids.setReadOnly(True)
        self.OutFluid_InsolubleSolids.setObjectName(_fromUtf8("OutFluid_InsolubleSolids"))
        self.OutFluid_Purity = QtGui.QLineEdit(self.Output_fluid_GrBx)
        self.OutFluid_Purity.setGeometry(QtCore.QRect(140, 107, 41, 20))
        self.OutFluid_Purity.setReadOnly(True)
        self.OutFluid_Purity.setObjectName(_fromUtf8("OutFluid_Purity"))
        self.label_OutFluid_InsolubleSolids = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_InsolubleSolids.setGeometry(QtCore.QRect(10, 87, 121, 16))
        self.label_OutFluid_InsolubleSolids.setObjectName(_fromUtf8("label_OutFluid_InsolubleSolids"))
        self.label_OutFluid_pH = QtGui.QLabel(self.Output_fluid_GrBx)
        self.label_OutFluid_pH.setGeometry(QtCore.QRect(10, 131, 121, 16))
        self.label_OutFluid_pH.setObjectName(_fromUtf8("label_OutFluid_pH"))
        self.Tank_tabWidget.addTab(self.Tank_tab_2, _fromUtf8(""))
        self.Tank_tab_3 = QtGui.QWidget()
        self.Tank_tab_3.setObjectName(_fromUtf8("Tank_tab_3"))
        self.label = QtGui.QLabel(self.Tank_tab_3)
        self.label.setGeometry(QtCore.QRect(16, 12, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.Tank_tabWidget.addTab(self.Tank_tab_3, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.Tank_tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.Physical_properties_GrBx.setTitle(_translate("Dialog", "Propiedades físicas", None))
        self.label_Cross_Sectional_Area.setText(_translate("Dialog", "Área transversal [m2]", None))
        self.label_Volumen.setText(_translate("Dialog", "Volumen [m3]", None))
        self.Initial_conditions_GrBx.setTitle(_translate("Dialog", "Condiciones iniciales", None))
        self.label_Initial_Level.setText(_translate("Dialog", "Nivel del tanque [°C]", None))
        self.OKButton_Tank.setText(_translate("Dialog", "Aceptar", None))
        self.Tank_tabWidget.setTabText(self.Tank_tabWidget.indexOf(self.Tank_tab_1), _translate("Dialog", "Propiedades físicas", None))
        self.Input_fluid_GrBx.setTitle(_translate("Dialog", "Fluido de entrada", None))
        self.label_InFluid_Flow.setText(_translate("Dialog", "Flujo másico [t/h]", None))
        self.label_InFluid_Temp.setText(_translate("Dialog", "Temperatura [°C]", None))
        self.label_InFluid_Brix.setText(_translate("Dialog", "Brix [kg/kg]", None))
        self.label_InFluid_Purity.setText(_translate("Dialog", "Pureza [kg/kg]", None))
        self.label_InFluid_InsolubleSolids.setText(_translate("Dialog", "Sólidos insolubles [kg/kg]", None))
        self.label_InFluid_pH.setText(_translate("Dialog", "pH ", None))
        self.Output_fluid_GrBx.setTitle(_translate("Dialog", "Fluido de salida", None))
        self.label_OutFluid_Flow.setText(_translate("Dialog", "Flujo másico [t/h]", None))
        self.label_OutFluid_Temp.setText(_translate("Dialog", "Temperatura [°C]", None))
        self.label_OutFluid_Brix.setText(_translate("Dialog", "Brix [kg/kg]", None))
        self.label_OutFluid_Purity.setText(_translate("Dialog", "Pureza [kg/kg]", None))
        self.label_OutFluid_InsolubleSolids.setText(_translate("Dialog", "Sólidos insolubles [kg/kg]", None))
        self.label_OutFluid_pH.setText(_translate("Dialog", "pH ", None))
        self.Tank_tabWidget.setTabText(self.Tank_tabWidget.indexOf(self.Tank_tab_2), _translate("Dialog", "Variables de proceso", None))
        self.label.setText(_translate("Dialog", "Nivel en tanque:", None))
        self.Tank_tabWidget.setTabText(self.Tank_tabWidget.indexOf(self.Tank_tab_3), _translate("Dialog", "Gráfica", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

